### ISSUE TITLE
Support for Rails 4

### ISSUE THREAD

**Issue by Olgagr** [markburns/to_factory#6] opened 2015-01-10 07:27 UTC
Please add support for Rails 4 applications.

**Comment by markburns** [comment] 2015-01-10 07:28
We both created this at the same time - closing as a duplicate of #7

**Comment by Olgagr** [comment] 2015-01-10 07:29
I've just want to do it :)

**Closed by markburns** 2015-01-10 07:28 UTC

**Comment by markburns** [comment] 2015-01-10 07:33
Sorry - actually it was pretty arbitrary for me to close this one - I went to read it after creating the other one.

Did you mean you want to add the Rails 4 support? That would be awesome if so.
My first thoughts are that it would be too complicated supporting Rails 2 and ruby 1.8.7 and Rails 4 in the same codebase - so we'll need a branch for > Rails 4 and release separate versions.

If you are thinking of doing it I won't look at it and give you a chance to add it
